### ISSUE TITLE
Будит ли обнова до 1.16.3? 

### ISSUE THREAD

**Issue by Sepera-okeq** [Brikster/Chatty#107]
Будет ли апдейт плагина до 1.16.3? Пока что снапшот хреново работает. Есть какие-то странные ошибки, плюс нельзя услышать или прочитать сообщения в Global/Local чатах (хотя в консоли все прекрасно пишется)

Ядро Тунити (fork Paper)

**Comment by Brikster** [comment]
Когда-нибудь будет, как только - так сразу.
