### ISSUE TITLE
Не работает HEX в лорах предметов

### ISSUE THREAD

**Issue by iBuseWinner** [Brikster/Chatty#111]
Ну, как-то так.
Это, к слову, placeholder от плагина Guilds.
В чате показывается нормально, в JSON нет.
![image](https://user-images.githubusercontent.com/44753872/103353776-cab27e80-4aba-11eb-8266-da7e38fb9d15.png)

**Comment by Brikster** [comment]
Это лор предмета или текст который при наведении на что-то в чате отображается?

**Comment by iBuseWinner** [comment]
Ой, это лор при наведении на ник игрока.

**Comment by Brikster** [comment]
Пофиксил в @9ae2b5d.
