### ISSUE TITLE
Не работает Hex Colors в чате.

### ISSUE THREAD

**Issue by CrazyL3gend** [Brikster/Chatty#113]
В общем, я пытаюсь использовать Hex, в формате чате, но сам чат показывает это так ->
![Снимок](https://user-images.githubusercontent.com/63064550/106399930-9ff67580-642c-11eb-8bda-5ff09b3634e6.PNG)
сам конфиг выглядит так ->
![image](https://user-images.githubusercontent.com/63064550/106399961-c0becb00-642c-11eb-82a2-e8247faf3858.png)

**Comment by Brikster** [comment]
А какую версию вы использовали? Билд для 1.16 (2.19-SNAPSHOT)?
