### ISSUE TITLE
[] Перед сообщением

### ISSUE THREAD

**Issue by Anarchist-byte** [Brikster/Chatty#115]
Конфиг чата: 
  local:
    enable: true
    format: '&eL &7| {prefix}{player}{suffix}: {message}'
    range: 100
    cooldown: -1
    command: 'localchat'

Сообщение выглядит так: []L | ник: g

Как убрать квадратные скобки?

**Comment by OstriySous-dev** [comment]
Тоже самое. Из плагинов ну максимум CMI.

**Comment by Brikster** [comment]
Нужны список плагинов и логи, без этого вряд ли получится разобраться.

**Comment by OstriySous-dev** [comment]
Пофиксил очень просто. Multiverse-Core/config.yml/:
`  prefixchat: 'false'
  prefixchatformat: '[%world%]%chat%'` 
  он видимо к миру по умолчанию название не присваивает и из-за этого даже не ясно откуда такая штукенция идет

**Comment by Brikster** [comment]
Понятно, ну это типичная проблема) Непонятно, зачем в Multiverse-Core эта фича по-умолчанию включена.
