### ISSUE TITLE
[world] shows when i chat

### ISSUE THREAD

**Issue by PiglerthePig** [Brikster/Chatty#121]
![2021-05-18_17 06 56](https://user-images.githubusercontent.com/54480937/118625756-dbab2480-b7fc-11eb-8245-74ac8967b7c9.png)

how can i disable this?

**Comment by Brikster** [comment]
It's seems to be a Multiverse-Core feature. Try to disable world prefix in Multiverse-Core configuration.

**Comment by PiglerthePig** [comment]
> It's seems to be a Multiverse-Core feature. Try to disable world prefix in Multiverse-Core configuration.

thanks alot, that was the issue.
