### ISSUE TITLE
Hex color don't work

### ISSUE THREAD

**Issue by VINRED5** [Brikster/Chatty#127]
![image](https://user-images.githubusercontent.com/74217586/126066246-e4850b24-7752-4cb1-be2a-1ffe6a8ebabc.png)

**Comment by Brikster** [comment]
Please, show your config.yml (`chats` section)

**Comment by VINRED5** [comment]
Sorry, I understand what the reason is. I used the wrong gradient format. It is possible to add the format {#hexcode>}text{#hexcode<}

**Comment by VINRED5** [comment]
This format is used in the CMI and TAB plugins. Without this format, I will not be able to make a gradient in the prefix and in the nickname
