### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by xstmass** [Brikster/Chatty#130]
1.7.10, последняя версия. Из всех настроек включен только json, больше ничего не изменялось.
https://www.pastery.net/nrantg/

**Comment by Serega007RU** [comment]
А как проблему то решили?

**Comment by xstmass** [comment]
> А как проблему то решили?

Не проверял еще, но в ПРах вроде как есть фикс

**Comment by Serega007RU** [comment]
Да, уже увидел
