### ISSUE TITLE
Доступ к форматированию

### ISSUE THREAD

**Issue by SkyWatcher2019** [Brikster/Chatty#158]
Игроки могут использовать форматирование чата
![image](https://user-images.githubusercontent.com/62600934/161154134-5a0b6ba2-ed5d-4ce9-a3cf-4308c6ae63b3.png)
![image](https://user-images.githubusercontent.com/62600934/161154169-18bcbee7-633f-4d55-ab7e-a65702aeea5b.png)
однако прав `chatty.style.<style>` у них нет
![image](https://user-images.githubusercontent.com/62600934/161154235-4aa17fa9-e77c-450c-8ea5-0f888bfedfcd.png)
Chatty version 2.19.5, Pufferfish version git-Pufferfish-59

**Comment by Brikster** [comment]
Несколько раз обращались с такой проблемой. Каждый раз выяснялось, что проблема не в Chatty)
Думаю, какой-то другой плагин преобразовывает цвета (мб Essentials).

**Comment by SkyWatcher2019** [comment]
Essentials работает с чатом через EssentialsChat, да и нет у нас его

**Comment by SkyWatcher2019** [comment]
Нашел в #157 

> При включении json сообщений, нет проверки на chatty.style право. Любой игрок без права может делать цветные сообщения.

**Comment by Kapitowa** [comment]
> Несколько раз обращались с такой проблемой. Каждый раз выяснялось, что проблема не в Chatty) Думаю, какой-то другой плагин преобразовывает цвета (мб Essentials).

это происходит на последнем билде paper 1.18.2 без плагинов

**Comment by Brikster** [comment]
Исправлено. Наконец-то смог отловить ошибку, спасибо.
Возникала при наличии права `chatty.mentions`.
