### ISSUE TITLE
Предложение: добавить возможность удалять сообщения

### ISSUE THREAD

**Issue by Cactus998** [Brikster/Chatty#178]
Хотелось бы функцию удаления сообщения путем клика на кнопку. Причем кнопка будет кликабельна только игрокам с определенным правом. Примерно как на этом скрине

![maxresdefault](https://user-images.githubusercontent.com/108695149/177210026-053f58ba-d845-4a49-85d2-aa62d84d7011.jpg)

**Comment by Brikster** [comment]
А откуда этот скрин?

**Comment by Cactus998** [comment]
с обложки какого-то видео на ютубе. https://youtu.be/yFLIUUsLTh0

**Comment by Brikster** [comment]
Майнкрафт не позволяет изменять уже отправленное сообщение. В этом видео разработчик сохраняет все сообщения, которые отправляются игроку, и при изменении одного из них переотправляет последние N сообщений. Это чревато проблемами, например, при использовании BungeeCord, который тоже умеет отправлять сообщения. Слишком костыльное решение. К сожалению, вряд ли буду это реализовывать.

**Comment by Cactus998** [comment]
Эх, жалко. Возможно через пару лет выйдет обнова где поменяют систему чата
