### ISSUE TITLE
Предложение: стили/темы для чата

### ISSUE THREAD

**Issue by B1RDOW** [Brikster/Chatty#187]
### Допустим мы выбираем цвет чата при помощи меню или комманды.

![javaw_WsatdB1XXR](https://user-images.githubusercontent.com/61405779/187971096-0b1ccc95-2f22-47c5-a793-965271ae9401.png)

### И все последующие входящие сообщения изменяют цвет на выбранный.

![javaw_3uMZTKSagj](https://user-images.githubusercontent.com/61405779/187971480-1dc6ad4f-6f90-497a-a72a-29ac0e6043ea.png)
![javaw_nflXfmRor9](https://user-images.githubusercontent.com/61405779/187971487-8d54e422-347f-4803-acc5-ea5f244f7cb8.png)

### Пример данного чата можно увидеть на сервере spworlds

**Comment by Brikster** [comment]
Я стараюсь отдавать приоритет функционалу, который очень затруднительно сделать другими средствами, и являющемуся более "глобальным". Подобную же вещь можно легко сделать через JavaScript Expansion для PlaceholderAPI + DeluxeMenus - слишком узкий функционал добавлять в плагин было бы не очень разумно.
