### ISSUE TITLE
Not working placeholders in PM format

### ISSUE THREAD

**Issue by HamerLolKekChegoo** [Brikster/Chatty#192]
Input:
![image](https://user-images.githubusercontent.com/88581699/191056983-ec8794b5-960a-4f2f-a302-67731a494537.png)
Output:
![image](https://user-images.githubusercontent.com/88581699/191057043-334f5e70-286c-40f9-b8bf-90004c8b7225.png)

**Comment by TheAIprod** [comment]
Having the exact same issue.

**Comment by Brikster** [comment]
Unfortunately, current version of Chatty doesn't support placeholders in PM.
