### ISSUE TITLE
Добавление нового функционала (Поля header & footer в Автосообщениях)

### ISSUE THREAD

**Issue by WhiTe-Yak** [Brikster/Chatty#194]
Предлагаю добавить два параметра в конфигурационный файл, для возможности добавлять пробелы до и после автосообщения.
Пример взял из плагина ChatManager
![изображение](https://user-images.githubusercontent.com/53398532/194385658-cd5e063a-2ac7-4ba3-86d8-c37fd7f6cf34.png)

**Comment by VINRED5** [comment]
Если я правильно тебя понял, то попробуй "\nСообщение\n" или "&f\nСообщение\n&f"
