### ISSUE TITLE
Воспроизведение звука вместе с сообщение

### ISSUE THREAD

**Issue by VINRED5** [Brikster/Chatty#196]
Можно ли как-то сделать, чтобы не для всех чатов был звук, а для каждого свой?
К примеру, чтобы после отправки сообщения, люди, который имеют разрешения на этот чат слышали звук открывания двери

**Comment by Brikster** [comment]
Да, есть [пример].(https://github.com/Brikster/Chatty/blob/0c026252f4da410f38d594523965fe6dd2dc5c13/spigot/src/main/resources/config.yml#L116)

**Comment by VINRED5** [comment]
Так это звук для всех чатов, разве нет? Мне нужно разные звуки на разные чаты, для локального один звук, для глобального другой звук

**Comment by Brikster** [comment]
Это звук для одного чата. Указывается в секции конфига для конкретного чата.
