### ISSUE TITLE
Regex Filters Not Working

### ISSUE THREAD

**Issue by F3F5** [Brikster/Chatty#220]
Other plugins for example can catch f3f5 ru but chatty no
 https://pastes.dev/WpEkjZEkqu
so not working filters

**Comment by imDaniX** [comment]
You can't use duplicate keys in the config section, so only one `ip` and only one `web` expressions. Also, there's no `domain` key in the original - use `web` instead.

**Comment by F3F5** [comment]
> You can't use duplicate keys in the config section, so only one `ip` and only one `web` expressions. Also, there's no `domain` key in the original - use `web` instead.

i tested with some random names:
i can't
