### ISSUE TITLE
Где взять достоверную документацию по плагину?

### ISSUE THREAD

**Issue by WhiTe-Yak** [Brikster/Chatty#273]
В Wiki написано про версию 3, однако в последних обновлениях плагина есть только 2-е версии.
Когда ждать актуальную версию?

**Comment by Brikster** [comment]
В ветке v3 (сейчас основная) находится актуальный код. Эта версия сейчас в доработке, предварительные билды можно скачать в разделе Actions. Сейчас плагин достаточно стабилен, ещё немного времени и я выпущу релиз.
