### ISSUE TITLE
[v3] Поддержка DiscordSRV

### ISSUE THREAD

**Issue by c1oudychan** [Brikster/Chatty#274]
Сейчас оно определяет все чаты как один. Ему пофигу Локальный, Глобальный, ЕщеКакой-то.
![image](https://github.com/Brikster/Chatty/assets/96329203/2cf5afa4-4667-4300-b233-ffacc051f913)

Проблема также была репортнута в тикет ДискордСРВ (в их Дискорд)

**Comment by Brikster** [comment]
К релизу новой версии я сделаю pull request в репозиторий DiscordSRV. Если нужен мой предварительный билд DiscordSRV, который работает с новой версией, можете обратиться в ЛС в ТГ (t.me/brikster).
