### ISSUE TITLE
Commands for private messaging not available to players in Chatty 3.0.0

### ISSUE THREAD

**Issue by DimaSergeew** [Brikster/Chatty#281]
When attempting to use the private messaging commands (/me, /m, /w, /msg) in Chatty version 3.0.0, players receive a message indicating that these commands do not exist. This issue persists despite the players attempting to use the commands as intended for private communication. However, when logged in as an administrator, these commands can be executed without any issues, suggesting that the problem lies with a missing permission that should allow players to access these commands. This discrepancy between player and administrator capabilities hinders the intended functionality of the plugin, as it fails to provide a means for players to communicate privately.

**Comment by c1oudychan** [comment]
Try to give `chatty.command.msg` & `chatty.command.pm` permissions
And `chatty.pm`
