### ISSUE TITLE
PROBLEM WITH ALL COLOR PERMISSIONS.

### ISSUE THREAD

**Issue by jagermeizter** [Brikster/Chatty#287]
None of these permissions work:
chatty.style.<style> or chatty.style.<style>.<chat>

I tried all of these:

```
chatty.style.colors
chatty.style.colors.local
chatty.style.colors.global

chatty.style.bold
chatty.style.bold.local
chatty.style.bold.global

chatty.style.italic
chatty.style.italic.local
chatty.style.italic.global

chatty.style.magic
chatty.style.magic.local
chatty.style.magic.global

chatty.style.reset
chatty.style.reset.local
chatty.style.reset.global

chatty.style.underline
chatty.style.underline.local
chatty.style.underline.global

chatty.style.strikethrough
chatty.style.strikethrough.local
chatty.style.strikethrough.global
```

**COLORS AND OTHERS ONLY WORK WITH OP.**
The problem is the permissions, they are broken. In fact, when using Tab Complet it does not detect _.style_ in the permissions system, it is as if they did not exist in the code (They do exist, because if not, with OP it would not detect anything).

I am using Chatty v3 #113. PaperMC Version 1.20.4 Build#459. I use Luckperms for the permissions system.

**Comment by Brikster** [comment]
Unfortunately, we don't have Wiki page in English for Chatty v3 yet, but you can translate [this page](https://github.com/Brikster/Chatty/wiki/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%8B-%D0%B8-%D0%BF%D1%80%D0%B0%D0%B2%D0%B0) with online translator to get information about new permissions for color codes.
