### ISSUE TITLE
[v3] Добавьте поддержку плейсхолдера {player} в MiniMessage когда используешь hover/click ивенты. 

### ISSUE THREAD

**Issue by deilyyxx** [Brikster/Chatty#295]
[v3] Добавьте поддержку плейсхолдера {player} в MiniMessage когда используешь hover/click ивенты. 

Не работает в 'chats.yml', хочу сделать чтобы можно было нажать на ник игрока и предложится команда '/msg {player}' но предлагается команда '/msg {player}' без замены плейсхолдера. Не знаю связано ли это с MiniMessage, но баг остаётся багом.

**Comment by Brikster** [comment]
Попробуйте использовать плейсхолдер %player_name% из PlaceholderAPI. Плейсхолдер {player} существенно ограничен, я не рекомендую его использовать, если только у вас не ванильный сервер без PAPI.

**Comment by deilyyxx** [comment]
Большое спасибо!
