### ISSUE TITLE
[v3] Revert #ffffff format

### ISSUE THREAD

**Issue by c1oudychan** [Brikster/Chatty#296]
![image](https://github.com/Brikster/Chatty/assets/96329203/cd4caefc-2a72-4941-b6ec-c4f839f9c2c2)
Он ломает даже уже существующие штуки в конфиге.

Удалите этот формат, он просто мешает

**Comment by Brikster** [comment]
Поддержка формата убрана в 3f12e627c15b83f8e2f3cacc2b2cc6016d8954f5.
