### ISSUE TITLE
[v3] Chat channels in version 3.0.0 shapshot are no longer different for another plugins

### ISSUE THREAD

**Issue by trc99** [Brikster/Chatty#297]
in old versions of Chatty, when using any plugins like DiscordSRV, it was possible to explicitly specify the name of the chat from chatty in the config of other plugins, now, as far as I understand, the chatty code has been rewritten and now, when specifying any of the chat names in other plugins, they still see and local and global chat at once, and not just one indicated, I don’t know what to do with this, you can write this is a Chatty bug or not

i used Chatty-3.0.0-SNAPSHOT

**Comment by trc99** [comment]
![изображение](https://github.com/Brikster/Chatty/assets/57718209/2910a7bb-3f18-41ec-abe7-b4e5487ae23a)
first - 3.0.0
second - 2,19.14

ps. don’t pay attention to the chat style, this happens with any formatting

**Comment by c1oudychan** [comment]
1. Ты можешь писать на русском, Brikster все понимает.
2. Уже есть PR в DiscordSRV для его поддержки. Если хочешь можешь сделать сам билд. https://github.com/DiscordSRV/DiscordSRV/pull/1648

**Comment by trc99** [comment]
отдуши бро

**Comment by sub-kek** [comment]
> 1. Ты можешь писать на русском, Brikster все понимает.
> 
>     2. Уже есть PR в DiscordSRV для его поддержки. Если хочешь можешь сделать сам билд. [Update Chatty api to 3.0.0-SNAPSHOT DiscordSRV/DiscordSRV#1648](https://github.com/DiscordSRV/DiscordSRV/pull/1648)

Да только я нем слегка налажал. displayname вместо id чата использую. Если его и использовать то когда у меня дойдут руки новый PR кинуть со всеми исправлениями и поддержкой обоих версий чатти.
