### ISSUE TITLE
Crashing server when entering the command tell, msg, etc

### ISSUE THREAD

**Issue by ghost** [Brikster/Chatty#316]
# Description
**When entering msg/tell and other similar commands, the server gives an error and crashes.**

- Config: [config.txt](https://github.com/user-attachments/files/16457518/config.txt) (txt because you can't yml)
- Crash-log: [crash-2024-08-01_13.36.16-server.txt](https://github.com/user-attachments/files/16457525/crash-2024-08-01_13.36.16-server.txt)

**Comment by ghost** [comment]
Перевод на рус
# Описание
**При вводе команд tell/msg и других сервер крашится**

**Comment by wshuw** [comment]
Нашел решение ошибки?

**Comment by ghost** [comment]
> Нашел решение ошибки?

chatex поставил попросту
