### ISSUE TITLE
[v3] Hide Quit/Join permission

### ISSUE THREAD

**Issue by Rinary1** [Brikster/Chatty#331]
Суть предложения вот в чём:
Добавить Permission, который будет прятать сообщение о входе и выходе. Очень актуально для администрации.

**Comment by Brikster** [comment]
Речь о том, чтобы игроки с правом не видели чужие сообщения? Или чтобы при наличии права сообщение о твоём входе/выходе не отображалось? Если речь о втором, то есть permission'ы на обратное поведение (отображение сообщения только при наличии права). В плагинах на права можно забрать право для определённых групп, даже если рядом ей добавлена "*".  Тогда обычным игрокам право можно выдать, и всё будет работать, как вами задумано.

**Comment by Rinary1** [comment]
> Речь о том, чтобы игроки с правом не видели чужие сообщения? Или чтобы при наличии права сообщение о твоём входе/выходе не отображалось? Если речь о втором, то есть permission'ы на обратное поведение (отображение сообщения только при наличии права). В плагинах на права можно забрать право для определённых групп, даже если рядом ей добавлена "*". Тогда обычным игрокам право можно выдать, и всё будет работать, как вами задумано.

окей, понял
