### ISSUE TITLE
Вайтлист матов не различает регистр символов

### ISSUE THREAD

**Issue by SSKirillSS** [Brikster/Chatty#53]
Использую фильтр от VirtualMaks, добавил в вайтлист слово "корабля". Если в игре ввожу это слово строчными символами - всё нормально, но если хоть одна буква будет верхнего регистра - считает за мат.
Не знаю, проблема плагина это или фильтра, но выглядит так, будто первое.

Версия от 30 марта 2020.

**Comment by Brikster** [comment]
Пофикшено.
