### ISSUE TITLE
Опция блокировки капса

### ISSUE THREAD

**Issue by SSKirillSS** [Brikster/Chatty#54]
В файле конфигурации есть раздел moderation/caps/block, он по дефолту стоит на true. В описании к нему сказано, что если поставить на false, то сообщения будут отсылаться в нижнем регистре. Вне зависимости от того, что стоит в этой опции, сообщения всегда отправляются в нижнем регистре, если система капса их детектит.

Также, было бы неплохо, если бы в нижний опускало не всё сообщение, а, например, вот так:
Из...
ПРИВЕТ, КАК ДЕЛА? У МЕНЯ ОТЛИЧНО!
В...
Привет, как дела? У меня отлично!

Т.е. после знаков препинания, обозначающих конец предложения первый символ писать с большой буквы. Также, первый символ в предложении тоже писать с большой.

<3

**Comment by Brikster** [comment]
К сожалению, не думаю, что есть особый смысл это делать, но фича интересная)
