### ISSUE TITLE
Расширение опции замены мата

### ISSUE THREAD

**Issue by SSKirillSS** [Brikster/Chatty#55]
В данный момент мат может быть заменён на слово, указанное в поле moderation/swear/replacement. И, как я понимаю, такое слово может быть всего одно. Было бы неплохо, если бы эта опция поддерживала несколько предложенных слов, и при виде мата в чате заменяла на случайное из этого списка (моя основная цель в данном случае - заменять мат на звуки животных :3).

Совсем-совсем в идеале добавить поддержку форматирования текста, т.е. возможность окрасить слово, на которое будет заменяться мат. В качестве временной меры можно использовать окрашивание при помощи символа §, но с ним довольно неудобно работать, если есть несколько групп, и у каждой свой цвет текста.

<3

**Comment by Brikster** [comment]
В следующем обновлении будет окрашивание слова-замены.

**Comment by SSKirillSS** [comment]
@Brikster, не помню, было ли это добавлено в одном из предыдущих коммитов. Мб уже пора закрывать, и оно уже реализовано?

**Comment by Brikster** [comment]
d523360
