### ISSUE TITLE
JSON - Клик по цветному нику игрока

### ISSUE THREAD

**Issue by SSKirillSS** [Brikster/Chatty#56]
При включенном форматировании JSON клик по цветному нику с плейсхолдером {player} (без PlaceholedAPI) также копирует и скрытые символы, в результате я получаю: §4SSKirillSS§r. Соответственно, использование такого в команде вызовет отключение от сервера из-за использования некорректных знаков. Возможно ли это как-то исправить?

**Comment by Brikster** [comment]
В следующем обновлении исправлю.

**Comment by Brikster** [comment]
Исправлено.
