### ISSUE TITLE
JSON - Поддержка плейсхолдеров от других плагинов

### ISSUE THREAD

**Issue by SSKirillSS** [Brikster/Chatty#57]
Не знаю, нужно писать тут разработчикам этих самих плагинов, или сюда, но на всякий случай...

Я использую IridiumSkyBlock, в нём есть плейсхолдер, отображающий уровень острова - [ISLAND_LEVEL], его я добавил в префикс к игроку - всё работает отлично, но если добавляю в json/tooltip - эффекта нет, отображается просто название плейсхолдера. Можно ли как-то это исправить, или нужно писать разработчикам ISkyBlock?

**Comment by Brikster** [comment]
Если плагин не поддерживает PlaceholderAPI, то это к его разработчикам.

**Comment by SSKirillSS** [comment]
Забыли. Я посмотрел как реализованы эти плейсхолдеры, оно их тянет только в обычном строчном форматировании чата. Для JSONa надо юзать обычные PAPI плейсхолдеры.

Спасибо.
