### ISSUE TITLE
Logs work when they are disabled in the config

### ISSUE THREAD

**Issue by AlekseyVideman** [Brikster/Chatty#60]
Здравствуйте! Такая вот проблема: в конфиге отключено логирование чата, но в папке /logs продолжают появляться log-файлы.
Конфиг-файл не резал, удалён только один блок - сообщения о гибели игрока. Помогите пожалуйста. Спасибо!

**Comment by Brikster** [comment]
В следующем обновлении исправлю, спасибо.
