### ISSUE TITLE
[Bug] [1.16.1] Some placeholders don't work

### ISSUE THREAD

**Issue by AlekseyVideman** [Brikster/Chatty#63]
Hello!
Placeholders don't work on 1.16: {player}, {sender-name}, {recipient-name}

Server: Paper, 1.16.1

**Comment by SSKirillSS** [comment]
If someone watches into this issue and doesn't understand:
He wants to say that pre-made `{player}`, `{sender-name}` and `{recipient-name}` placeholders doesn't work on 1.16.1 Paper. 

Также, следует отметить, что разработчик говорит по-русски, соответственно, обращения можно писать и так.

**Comment by Brikster** [comment]
Is it about pm-format ?

**Comment by AlekseyVideman** [comment]
> Is it about pm-format ?

Yes. Placeholders also don't work in join/quit messages

**Comment by AlekseyVideman** [comment]
I'm sorry to bother you. All functions work perfectly.
Maybe the problem was the Paper...
