### ISSUE TITLE
Локализация наименований каналов чата

### ISSUE THREAD

**Issue by SSKirillSS** [Brikster/Chatty#65]
На данный момент при переключении между чатами выводится сообщение `Вы перешли в чат "local/global/etc"`. Было бы неплохо создать для каждого канала возможность задать название на русском языке, дабы не использовать оригинальное наименование объекта.

**Comment by Brikster** [comment]
Возможно, потом добавлю display name

**Comment by Brikster** [comment]
Добавлено в 67e7b2c
