### ISSUE TITLE
Перечень слов для автоматического переключения между каналами чата

### ISSUE THREAD

**Issue by SSKirillSS** [Brikster/Chatty#66]
Принцип предельно прост: Если в сообщении игрока есть слова из списка, то это сообщение пересылается в определенный канал чата.
Где это может быть полезно? - Представим ситуацию, когда у вас есть торговый чат. В большинстве случаев на него всем всё равно, но... Я ХОЧУ ТОРГОВЫЙ ЧАТ. Так вот, если в сообщении игрока детектится "Продам" или "Куплю", то это сообщение автоматом пересылается в торговый.
Думаю, спектр применений этой функции куда шире, но в ситуации с торговым чатом это довольно неплохо звучит.

**Comment by Brikster** [comment]
Слишком частный случай. Если придумаю что-то более универсальное - сделаю.
