### ISSUE TITLE
Звук для аннонсера

### ISSUE THREAD

**Issue by SSKirillSS** [Brikster/Chatty#67]
Примитивная опция, проигрывающая указанный звук при выводе в чат/другие_места сообщение от аннонсера. Было бы неплохо сделать возможность выбора звука для каждой группы сообщений.

**Comment by LeetPlm4** [comment]
ЛЯ, ЧЕЛ, СПАСИБО!!! ТЫ МНЕ ТАКУЮ ИДЕЮ ПОДАЛ :D !!! 

тебе нужен плейсхолдер Sound
`/papi ecloud download Sound`

Думаю как им пользоваться в вики плейсхолдеров найдешь сам)

Вот тебе список всех звуков
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html

Для теста ставишь куда то в конец чата %sound_all_ENTITY_ENDERMAN_SCREAM-100-1% и наслаждаешься весельем)

**Comment by SSKirillSS** [comment]
Лол. Неплохая идея, спасибо :D

Но проблема с https://github.com/Brikster/Chatty/issues/74 всё ещё актуальна, потому плейсхолдеры в аннонсере у меня не парсятся.

**Comment by Brikster** [comment]
Добавил поддержку PlaceholderAPI в notifications.
