### ISSUE TITLE
Проблема с AdvancedMentions/DeluxeMentions и им подобными

### ISSUE THREAD

**Issue by SSKirillSS** [Brikster/Chatty#73]
При упоминании игрока в чате происходит следующее:
https://pastebin.com/kLyQA7W0

Само упоминание работает корректно, игрок получает уведомление, но вот ошибками спамит знатно.
Было бы неплохо либо добавить фичу с упоминаниями в сам Chatty, либо дать возможность таким сообщениям идти только в глобал.

**Comment by Brikster** [comment]
Добавил mentions в de54577.
