### ISSUE TITLE
Поддержка PlaceholderAPI?

### ISSUE THREAD

**Issue by SSKirillSS** [Brikster/Chatty#74]
Мне почему-то казалось, что эта фишка включена вообще во все менеджеры чатов, но, почему-то, в Chatty этого либо нет, либо у меня это просто не работает.
Сообщения при входе/выходе, а также аннонсер, по неизвестной мне причине не вытягивают плейсхолдеры.
Пример сообщения входа на сервер:
![image](https://user-images.githubusercontent.com/38190325/87701255-59973d00-c7a0-11ea-85e8-c3851a7a7c99.png)
При условии, что `/papi parse me %luckperms_prefix%` работает отлично.

**Comment by LeetPlm4** [comment]
![image](https://user-images.githubusercontent.com/46025416/87758800-cf89bb80-c815-11ea-8509-9e8caf505920.png)

/papi ecloud download LuckPerms
/papi reload

если у тебя версия постарше
попробуй вместо % поставить <>
Вот с 1.14 пример 
![image](https://user-images.githubusercontent.com/46025416/87759012-41fa9b80-c816-11ea-9b21-e3ae46b0a958.png)

**Comment by SSKirillSS** [comment]
@LeetPlm4, 1.12.2 у меня. Расширение PAPI и все работает на другом менеджере чатов. Проблема в том, что плейсхолдеры не работают именно в автомесседжах и сообщениях входа/выхода игрока. В JSON`e и форматировании каналов чата все работает, конечно.

**Comment by LeetPlm4** [comment]
@SSKirillSS  Ну будем вместе ждать фиксов и обновы) Я вот жду поддержки банжи на 1.16...

**Comment by SSKirillSS** [comment]
https://github.com/Brikster/Chatty/commit/81cb230b4a5b1e139c22ac58352c0cf4d5b367d7#diff-004cda70e75dd2c62d0282cca10bb677R462
