### ISSUE TITLE
Пару идей связанные с префиксами\суффиксами.

### ISSUE THREAD

**Issue by LeetPlm4** [Brikster/Chatty#75]
1. Добавить возможность сохранять префиксы\суффиксы в msql, чат станет еще обширней в плане взаимодействия с банжой так как можно будет сделать общую базу для всех серверов. 
2. Вывести префиксы и суффиксы в плейсхолдеры, для того что бы их можно было использовать в том же табе или еще где (не знаю как правильно выразится если честно, надеюсь понятно)

3? discordSRV? нормальных чатов с его поддержкой попросту не существует....

Спасибо огромное за плагин <3 Это самый удобный, простой и легко настраиваемый чат который я встречала!

**Comment by LeetPlm4** [comment]
Также было бы не плохо иметь возможность отделять их от ваультовских (что-бы он не дублировал)

**Comment by Brikster** [comment]
API для DiscordSRV сделал, ждём действий от разработчика
