### ISSUE TITLE
Совместимость с Essentials Vanish

### ISSUE THREAD

**Issue by luckybl0ck** [Brikster/Chatty#76]
Когда игрок входит в ваниш, ему все еще можно писать личные сообщения. Можно ли сделать опцию для выключения этой возможности?

**Comment by perezzloy** [comment]
И для SuperVanish та же хрень. А еще, если пишешь в чат и есть только кто-то в ванише, то Чатти не пишет "Вас никто не услышал" и таким образом палит игрока в ванише.

**Comment by Brikster** [comment]
Добавлено в 0c84c36
