### ISSUE TITLE
не компилится chatty-spigot

### ISSUE THREAD

**Issue by levarar** [Brikster/Chatty#78]
При попытке скомпилить последний снапшот под 1.16 выходит сделать только chatty-api, под chatty-spigot оно не может обратится к нужным зависимостям, если я верно понял, из-за неработающего сайта.

Downloading from nametagedit-repo: http://ci.nametagedit.com/plugin/repository/everything/com/nametagedit/nametagedit/4.1.0/nametagedit-4.1.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Chatty 2.19-SNAPSHOT:
[INFO]
[INFO] Chatty ............................................. SUCCESS [  0.144 s]
[INFO] chatty-api ......................................... SUCCESS [  5.405 s]
[INFO] chatty-spigot ...................................... FAILURE [  1.387 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.148 s
[INFO] Finished at: 2020-07-19T19:43:05+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project chatty-spigot: Could not resolve dependencies for project ru.mrbrikster:chatty-spigot:jar:2.19-SNAPSHOT: Failed to collect dependencies at com.nametagedit:nametagedit:jar:4.1.0: Failed to read artifact descriptor for com.nametagedit:nametagedit:jar:4.1.0: Could not transfer artifact com.nametagedit:nametagedit:pom:4.1.0 from/to nametagedit-repo (http://ci.nametagedit.com/plugin/repository/everything/): Transfer failed for http://ci.nametagedit.com/plugin/repository/everything/com/nametagedit/nametagedit/4.1.0/nametagedit-4.1.0.pom 503 Service Unavailable -> [Help 1]

**Comment by Brikster** [comment]
Не собирается из-за упавшего репозитория NameTagEdit. Позже перенесу на свой, а то уж слишком часто он ложиться стал.

**Comment by levarar** [comment]
Это классно, ибо хотелось бы уже на сервер HEX завести, а менять привычный Chatty нет желания, поэтому будем ждать, благодарю.
