### ISSUE TITLE
Поддержка мультистрочного форматирования чата

### ISSUE THREAD

**Issue by SSKirillSS** [Brikster/Chatty#79]
Как и говорится в заглавии, было бы неплохо добавить возможность форматирования сообщений некоторых каналов в несколько строк. В качестве примера могу привести торговый чат. Обычно он ничем не отличается от других каналов, ведь  зачастую единственным отличительным признаком является префикс. В качестве решения этой проблемы можно добавить ему по одной строке-разделителю сверху и снизу, в результате получится что-то вроде этого:
```
===========================================
[Торговля] SSKirillSS: Продам стак алмазов!
===========================================
```
Собственно, предложение заключается в добавлении возможности в конфиге определить несколько строк для форматирования текста в определенном канале, а не одну.

**Comment by Brikster** [comment]
Добавлено в 5a31f04.
