### ISSUE TITLE
Собственные плейсхолдеры

### ISSUE THREAD

**Issue by SSKirillSS** [Brikster/Chatty#80]
Не знаю, почему не задумался об этом раньше. Предлагаю добавить несколько новых плейсхолдеров:
`%chatty_currentchat_{player_name}%` - Возвращает строку - название канала чата (а лучше displayname, о котором говорилось в одном из моих предложений), в котором находится указанный в скобках игрок.
`%chatty_chat_cooldown%` - Возвращает дробное значение (при желании можно округлить плейсхолдером math) задержки до отправки следующего сообщения.
`%chatty_playercount_{chat_channel_name}%` - Возвращает интовое значение - количество игроков, на данный момент находящихся в указанном канале чата.

**Comment by Brikster** [comment]
Добавлено в cbe18e98f97eabcc6e6d8712d16d5cd15ce78a92
