### ISSUE TITLE
Примерная дата выхода обновления?

### ISSUE THREAD

**Issue by LeetPlm4** [Brikster/Chatty#88]
Хотелось бы узнать когда выйдет новая версия с фиксами? 
Так же есть идея создать Discord сервер для связи.

**Comment by imDaniX** [comment]
Не автор, но скажу, что дев-билды можно скачать во вкладке "Actions".

**Comment by LeetPlm4** [comment]
> Не автор, но скажу, что дев-билды можно скачать во вкладке "Actions".

Дев билды это дев билды, они не всегда стабильны, в данном случаи плагин спамит в консоль ошибками.

**Comment by imDaniX** [comment]
> Дев билды это дев билды, они не всегда стабильны, в данном случаи плагин спамит в консоль ошибками.
> ![image](https://user-images.githubusercontent.com/46025416/88915648-5b1b3780-d26d-11ea-85f0-9adb00212856.png)

Такое репортить следует, желательно сюда на гитхаб, на случай если кто-нибудь решит поправить. Я сам закинул в плагин несколько функций. Если причина ошибок - я, будет проще исправить это именно мне, ибо код мне знаком.

**Comment by Brikster** [comment]
Эту ошибку уже пофиксил, причина - я)
