### ISSUE TITLE
Json components is not supported by Chatty on your server version

### ISSUE THREAD

**Issue by SSKirillSS** [Brikster/Chatty#95]
Использовал вот этот билд: https://github.com/Brikster/Chatty/actions/runs/192338972

Результат при отправке сообщения с включенным JSON: https://pastebin.com/k23HXp9c

Сервер: Mohist-1.12.2-a586242-server

**Comment by imDaniX** [comment]
Похоже, проблема с маппингами - в Chatty используются рефлексии для многих вещей, в том числе для json чата. Правильным решением было бы разделить некоторые функции плагина по версиям, возможно ещё на баккит и спигот... Но в таком случае проще уже будет переписывать плагин чуть ли не с нуля и при разработке учитывать возможность имплементации различных функций в по-разному.
Впрочем, наверняка есть варианты и проще. Возможно, как-то через ProtocolLib. В лучшем случае Mohist сами должны исправить это несоответствие, но сначала нужно ошибку копнуть глубже, ибо Chatty кидает собственную ошибку.

**Comment by SSKirillSS** [comment]
Самое странное в этом то, что последний релиз на мохисте работает нормально, а вот бета из GithubActions - неа.

**Comment by Brikster** [comment]
> Самое странное в этом то, что последний релиз на мохисте работает нормально, а вот бета из GithubActions - неа.

Последний релиз работает через костыль в виде команды /tellraw)))

**Comment by SSKirillSS** [comment]
Звучит страшно, но... Оно работает. Вернее.. Работало :D

**Comment by SSKirillSS** [comment]
@Brikster, привет. Удалось поговорить с одним из разработчиков. Результат:

![image](https://user-images.githubusercontent.com/38190325/90125580-f1218880-dd6a-11ea-9467-f1e211e43b51.png)
![image](https://user-images.githubusercontent.com/38190325/90125593-f54da600-dd6a-11ea-9b1f-05d7fa637a22.png)
`jsonToComponent is the method of mcp, it should be a in nms`

**Comment by Brikster** [comment]
8ac41c30c0e0e8bb0231d9a8a70d5f6bf033f85e
Попробовал поменять на "a".
Тестируйте :)

**Comment by SSKirillSS** [comment]
![image](https://user-images.githubusercontent.com/38190325/90128206-35af2300-dd6f-11ea-931a-1783932ff2d9.png)
Заработало. Спасибо!
