### ISSUE TITLE
Hex color codes

### ISSUE THREAD

**Issue by Shadowshiw** [Brikster/Chatty#96]
Hex color code not support in chat on SSSpigot

**Comment by Shadowshiw** [comment]
![2020-08-11_12 45 36](https://user-images.githubusercontent.com/69508791/89883721-3611b780-dbd1-11ea-8655-abd5ed9a0007.png)

**Comment by kenuna** [comment]
Try use " {#RRGGBB} "

**Comment by kenuna** [comment]
А. нет. Ничего не работает из-за того, что в чате Hex-цвета не поддерживаются, только перед твоим сообщением, все что ты укажешь тут:`{prefix} {player} {suffix} &8: <- {message}`
