### ISSUE TITLE
JSON в упоминании пользователя

### ISSUE THREAD

**Issue by SSKirillSS** [Brikster/Chatty#98]
При упоминании пользователя посредством символ @ и клике по части с этим упоминанием фрагмент конфига `suggest: '@{player} '` работает некорректно - он указывает на ник игрока, который кликает по упоминанию, а не ник игрока, который это упоминание использовал.

**Comment by Brikster** [comment]
Оно вообще должно указывать на ник упомянутого игрока.

**Comment by SSKirillSS** [comment]
Но, в таком случае, в чем смысл `suggest: '@{player} '`? Я думал, что это нужно для быстрого ответа на пинг от другого игрока, но чет.. Пока не могу найти применения.

**Comment by Brikster** [comment]
Как есть :)
Думаю, кто-то может найти применение.
